name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with: { submodules: recursive }

      - uses: oven-sh/setup-bun@v2
        with: { bun-version: latest }

      - run: bun ci
      - run: bun run lint
      - run: bun run check
